# Generated by Django 5.2.15 on 2026-06-11 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ladder_type', models.CharField(default='1v1', max_length=8, verbose_name='天梯类型')),
                ('season', models.IntegerField(verbose_name='赛季编号')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('mmr', models.IntegerField(default=1000, verbose_name='匹配分')),
                ('wins', models.IntegerField(default=0, verbose_name='胜场')),
                ('losses', models.IntegerField(default=0, verbose_name='负场')),
                ('disconnects', models.IntegerField(default=0, verbose_name='断线场次')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='账号')),
            ],
            options={
                'verbose_name': '天梯条目',
                'verbose_name_plural': '天梯条目',
                'indexes': [models.Index(fields=['ladder_type', 'season', '-points'], name='ladder_ladd_ladder__e76a2b_idx')],
                'unique_together': {('account', 'ladder_type', 'season')},
            },
        ),
    ]
