[General]
discordUrl=https://discord.gg/yxkVn4wBad

# Where game resources are located
gameresBaseUrl=//wyhjres2.bun.sh.cn/
mapsBaseUrl=//gameres.chronodivide.com/map/
modsBaseUrl=http://38.76.165.109:8899/mod/
gameResArchiveUrl=http://38.76.165.109:8899/fully-music.exe
patchNotesUrl=//chronodivide.com/patch-notes.html
ladderRulesUrl=//chronodivide.com/ladder-rules.html
modSdkUrl=https://github.com/chronodivide/mod-sdk
donateUrl=
breakingNewsUrl=
oldClientsBaseUrl=/old/
quickMatchEnabled=yes
botsEnabled=yes
# 默认联机区服(servers.ini 中的 section 名,与 lib/server-default.js 一致)
defaultServerRegion=local
debugLogging=wol
# Chronodivide 中国大区专供
defaultLanguage=zh-CN

viewport.width=1024
viewport.height=768

[CorsProxy]
# <originDomain>=<corsUrl>
# * will match any origin
# .<originDomain> will also match subdomains
archive.org="https://game.chronodivide.com/cors-proxy/?url="