"""
游戏中继服务(gserv)协议回复码。

与前端 dist/ra2web.min.js 中 network/gservCodes 模块逐项对应。
"""

RPL_CVERS_OK = 10
RPL_CVERS_OUTDATED = 11
RPL_CVERS_MISSING = 12

RPL_LOGGED_IN = 100
RPL_ALREADY_LOGGED_IN = 101
RPL_NOT_LOGGED_IN = 102
RPL_BAD_LOGIN = 103
RPL_TOO_MANY_LOGIN_ATTEMPTS = 104

RPL_INSTANCE_CREATED = 200
RPL_INSTANCE_EXISTS = 201
RPL_INSTANCE_TOO_MANY = 202

RPL_NOT_ENOUGH_PARAMS = 300
RPL_INVALID_PARAMS = 301
RPL_RATE_LIMIT_EXCEEDED = 302

RPL_INSTANCE_CONNECTED = 400
RPL_INSTANCE_NONEXISTENT = 401
RPL_INSTANCE_NOT_ALLOWED = 402
RPL_INSTANCE_ALREADY_STARTED = 403
RPL_NO_INSTANCE = 404
RPL_INSTANCE_NOT_RUNNING = 405
RPL_INSTANCE_VERS_MISMATCH = 406

RPL_GAME_OPTS = 500

RPL_LOAD_INFO = 600
RPL_MAP_TOO_BIG = 602
RPL_MAP_ALREADY_SENT = 603

RPL_GAME_START = 700

RPL_GAME_DESYNC = 801
RPL_NET_RATE = 802
RPL_TAUNT = 803
RPL_PLAYER_DISCONNECT = 804

# 二进制帧前缀与子命令(前端 gservCodes)
RPL_BIN_PREFIX = 2
RPL_BIN_GAME_ACTIONS = 1
RPL_BIN_MAP_DATA = 2

REQ_BIN_PREFIX = 2
REQ_BIN_GAME_ACTIONS = 1
REQ_BIN_GAME_STATE_HASH = 2
REQ_BIN_PUT_MAP = 3
REQ_BIN_GET_MAP = 4

# 前端 gservConfig
API_VERSION = 2
RECIPIENT_ALL = "#all"
RECIPIENT_TEAM = "#team"
TURN_TIMEOUT_MILLIS = 30_000
MAX_MAP_TRANSFER_BYTES = 2_097_152
