# Generated by Django 5.2.15 on 2026-06-11 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=64, unique=True, verbose_name='对局 id')),
                ('draw', models.BooleanField(default=False, verbose_name='平局')),
                ('settled_at', models.DateTimeField(auto_now_add=True, verbose_name='结算时间')),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranked_losses', to='accounts.account', verbose_name='败者')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranked_wins', to='accounts.account', verbose_name='胜者')),
            ],
            options={
                'verbose_name': '排位结算',
                'verbose_name_plural': '排位结算',
            },
        ),
        migrations.CreateModel(
            name='GameReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, max_length=64, verbose_name='对局 id')),
                ('tournament', models.BooleanField(default=False, verbose_name='排位赛')),
                ('finished', models.BooleanField(default=False, verbose_name='完赛')),
                ('out_of_sync', models.BooleanField(default=False, verbose_name='失步')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('map_name', models.CharField(blank=True, max_length=255, verbose_name='地图')),
                ('player_count', models.IntegerField(default=0, verbose_name='真人数')),
                ('start_time', models.BigIntegerField(default=0, verbose_name='开局时间戳')),
                ('raw_fields', models.JSONField(default=dict, verbose_name='完整字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='上报者')),
            ],
            options={
                'verbose_name': '战绩上报',
                'verbose_name_plural': '战绩上报',
                'unique_together': {('game_id', 'reporter')},
            },
        ),
    ]
