# Generated by Django 5.2.15 on 2026-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='用户名')),
                ('name_lower', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='用户名小写')),
                ('password_hash', models.CharField(max_length=128, verbose_name='密码哈希')),
                ('locale', models.IntegerField(default=0, verbose_name='地区代码')),
                ('banned', models.BooleanField(default=False, verbose_name='封禁')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最近登录')),
            ],
            options={
                'verbose_name': '玩家账号',
                'verbose_name_plural': '玩家账号',
            },
        ),
    ]
